# Generated by Django 5.2.15 on 2026-06-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_quiz_quizattempt_quizquestion_quizchoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True, default='', help_text='Textual lesson content / notes'),
        ),
    ]
