# Generated by Django 5.2.8 on 2026-07-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_cloudinary_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='courses/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='courses/lessons/'),
        ),
    ]
