# Generated by Django 5.2.8 on 2026-06-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reply',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
