from django.core.management.base import BaseCommand
from courses.models import Lesson

CONTENT = {
    "Introduction to Python": "Python is a high-level, interpreted language known for its clean syntax. In this lesson you'll set up your environment, run your first script, and understand how Python code is executed line by line.",
    "Variables and Data Types": "Variables store data in memory. Python supports strings, integers, floats, booleans, lists, tuples, dicts, and sets. Unlike statically-typed languages, Python infers types at runtime — no declarations needed.",
    "Control Flow": "Control flow determines which code runs and when. if/elif/else statements, for loops, while loops, and break/continue give you complete control over your program's execution path.",
    "Functions & Scope": "Functions are reusable blocks of code defined with def. Scope rules (LEGB: Local, Enclosing, Global, Built-in) determine where variables are visible. Use return to pass values back to the caller.",
    "Classes and Objects": "OOP models the world as objects with state (attributes) and behaviour (methods). A class is the blueprint; an object is an instance. Use __init__ as the constructor to initialise attributes.",
    "Inheritance": "Inheritance lets a child class reuse and extend a parent's behaviour. Call super().__init__() to initialise the parent. Python supports multiple inheritance via the MRO (Method Resolution Order).",
    "Polymorphism": "Polymorphism allows different classes to be used interchangeably when they share a common interface. Method overriding and duck typing make Python highly flexible and expressive.",
    "Decorators": "Decorators are functions that wrap other functions to add behaviour without modifying their source. The @syntax is sugar for func = decorator(func). Common uses: logging, authentication, caching.",
    "Web Scraper": "Build a scraper using requests and BeautifulSoup. Send HTTP GET requests, parse HTML, and extract data. Respect robots.txt, add delays, and handle pagination for ethical scraping.",
    "CLI Tool": "Command-line tools are scripts run from the terminal. Use argparse to accept arguments and flags. Structure your code with main() and use sys.exit() for proper exit codes.",
    "File Automation": "Python's os and shutil modules let you automate file operations: rename, move, copy, delete, and organise files programmatically. Great for cleaning downloads folders or batch-renaming assets.",
    "API Integration": "REST APIs exchange data over HTTP using JSON. Use the requests library to call endpoints, pass headers/auth tokens, and parse responses. Always handle status codes and timeouts gracefully.",
    "Component Architecture": "React UIs are built from composable, reusable components. Each component is a function returning JSX. Think in terms of parent-child trees — data flows down via props, events bubble up via callbacks.",
    "State & Props": "Props pass data from parent to child (read-only). State is local, mutable data managed with useState. When state changes, React re-renders the component and its subtree efficiently via the virtual DOM.",
    "Hooks Deep Dive": "Hooks let function components use state and lifecycle features. useState for local state, useEffect for side-effects, useRef for DOM refs, and useMemo/useCallback for performance optimisation.",
    "Context API": "Context solves prop-drilling by providing a global data store. createContext creates the store; Provider wraps consumers; useContext reads the value. Best for themes, auth, and locale — not for frequent updates.",
    "Models & Serializers": "Django models define your database schema as Python classes. DRF Serializers convert model instances to JSON and validate incoming data. ModelSerializer auto-generates fields from the model.",
    "API Views": "DRF provides APIView for manual control, generic views for CRUD shortcuts, and ViewSets for full REST resources. Use routers to auto-generate URL patterns from ViewSets.",
    "Authentication": "DRF supports session, token, and JWT authentication. JWT (JSON Web Token) is stateless: the server signs a payload, the client stores it and sends it in the Authorization header on every request.",
    "Permissions": "Permissions control who can access which endpoints. DRF provides IsAuthenticated, IsAdminUser, and IsAuthenticatedOrReadOnly. Write custom permissions by subclassing BasePermission.",
    "Connecting Frontend & Backend": "The React frontend communicates with Django via Axios HTTP calls. Configure CORS in Django to allow the React dev-server origin. Store the JWT in localStorage and attach it to every API request.",
    "Docker Setup": "Docker packages your app and its dependencies into a container. Write a Dockerfile for each service and a docker-compose.yml to wire them together. Use volumes to persist the database between restarts.",
    "AWS Deployment": "Deploy Django to an EC2 instance behind an Nginx reverse proxy with Gunicorn as the WSGI server. Store media files in S3, use RDS for PostgreSQL, and terminate SSL at the load balancer.",
    "CI/CD Pipeline": "CI/CD automates testing and deployment. GitHub Actions can run your test suite on every push and deploy to AWS on merge to main. Keep secrets in environment variables — never commit credentials.",
    "Empathize Phase": "Empathy is the foundation of human-centred design. Conduct user interviews, observe behaviour, and build empathy maps. The goal is to understand pain points deeply before jumping to solutions.",
    "Define & Ideate": "Synthesise your research into a clear problem statement (How Might We). Brainstorm solutions with Crazy 8s or mind-mapping. Prioritise ideas using an impact/effort matrix before committing to a solution.",
    "Prototyping Basics": "Prototypes test ideas cheaply before building. Start with paper sketches, progress to digital wireframes, then interactive prototypes. Fidelity should match the question you're trying to answer.",
    "Usability Testing": "Test with 5 users to uncover 85% of usability issues. Use think-aloud protocol, observe without leading, and note where users hesitate or fail. Iterate on findings before the next design sprint.",
    "Figma Interface Tour": "Figma is a cloud-based design tool with real-time collaboration. Learn the canvas, layers panel, properties panel, and toolbar. Frames are your artboards; use constraints for responsive layouts.",
    "Auto Layout": "Auto Layout makes frames resize dynamically. Set direction (horizontal/vertical), spacing, padding, and alignment. It mirrors CSS Flexbox, so your designs translate naturally to code.",
    "Components & Variants": "Components are reusable UI elements. Create a master component, then Variants for different states (default, hover, disabled). Swap variants in instances without breaking the design.",
    "Interactive Prototypes": "Connect frames with interactions to simulate user flows. Set triggers (tap, hover, drag), animations (smart animate, dissolve), and destinations. Share a prototype link for stakeholder review.",
    "Linear Regression": "Linear regression models the relationship between a continuous output and one or more inputs. Minimise mean squared error to find the best-fit line. Understand bias-variance tradeoff before adding complexity.",
    "Classification Algorithms": "Classification predicts discrete labels. Logistic Regression, k-NN, Decision Trees, and SVMs are core algorithms. Evaluate with accuracy, precision, recall, and F1-score — not just accuracy on imbalanced data.",
    "Model Evaluation": "Use train/validation/test splits or k-fold cross-validation. Watch for data leakage. Plot learning curves to diagnose underfitting (high bias) vs overfitting (high variance).",
    "Feature Engineering": "Raw data rarely feeds directly into models. Encode categoricals, normalise numerics, create interaction features, and handle missing values. Good features often matter more than algorithm choice.",
    "Neural Network Basics": "Neural networks are layers of neurons connected by weighted edges. Forward pass computes predictions; backpropagation computes gradients; gradient descent updates weights. Activation functions add non-linearity.",
    "CNNs for Vision": "Convolutional layers learn spatial filters automatically. Pooling reduces spatial dimensions. Stack conv-relu-pool blocks, then flatten and add dense layers for classification tasks.",
    "RNNs & LSTMs": "RNNs process sequences by maintaining hidden state. LSTMs solve the vanishing gradient problem with gates (input, forget, output). Use for time series, NLP, and any ordered data.",
    "Transfer Learning": "Pre-trained models (ResNet, BERT) encode general knowledge. Fine-tune on your domain by freezing early layers and training later ones. Achieves high accuracy with far less data and compute.",
    "Text Processing": "NLP starts with tokenisation, lowercasing, stop-word removal, and stemming/lemmatisation. Represent text as bag-of-words, TF-IDF, or dense word embeddings (Word2Vec, GloVe).",
    "Transformers & BERT": "Transformers use self-attention to model long-range dependencies in parallel. BERT is pre-trained bidirectionally on masked language modelling. Fine-tune it on classification, NER, or QA tasks.",
    "FastAPI Serving": "FastAPI is an async Python framework ideal for serving ML models. Load your model at startup, expose a /predict endpoint, validate inputs with Pydantic schemas, and return JSON predictions.",
    "Docker + AWS SageMaker": "Package your model in a Docker container following SageMaker's serving contract. Push to ECR, create a SageMaker endpoint, and autoscale based on request volume. Monitor with CloudWatch.",
    "Porter's 5 Forces": "Porter's framework assesses industry attractiveness: competitive rivalry, supplier power, buyer power, threat of substitutes, and threat of new entrants. Use it to identify strategic opportunities and risks.",
    "SWOT Analysis": "SWOT maps Strengths, Weaknesses, Opportunities, and Threats. Pair internal factors (S/W) with external factors (O/T) to generate strategic options: SO, WO, ST, and WT strategies.",
    "Business Model Canvas": "The BMC visualises nine building blocks: value proposition, customer segments, channels, relationships, revenue streams, key resources, activities, partners, and cost structure — on a single page.",
    "Value Proposition Design": "A strong VP solves customer jobs, relieves pains, and creates gains. Use the Value Proposition Canvas to map customer profile to your product map, then iterate until you reach product-market fit.",
    "Finding Product-Market Fit": "PMF is when a product satisfies strong market demand. Signal: users are disappointed if the product disappears (>40% 'very disappointed' in Sean Ellis survey). Achieve it by talking to users and iterating weekly.",
    "Fundraising 101": "Raise capital when you need it to accelerate, not survive. Know your burn rate and runway. For seed rounds, SAFEs and convertible notes are simpler than priced equity. Warm intros beat cold outreach.",
    "Team Building": "Early hires define culture. Hire for mission fit and learning velocity over specific skills. Balance technical and business talent. Establish clear ownership with a RACI matrix and regular 1:1s.",
    "Growth Hacking": "Growth hacking is rapid experimentation across marketing, product, and engineering to find scalable growth levers. Run A/B tests, optimise activation funnels, and invest in referral loops.",
    "Understanding Exposure": "Exposure is the amount of light reaching the sensor, controlled by aperture, shutter speed, and ISO — the Exposure Triangle. Correct exposure keeps highlights from blowing out and shadows with detail.",
    "Aperture & Depth of Field": "Aperture (f-stop) controls how much light enters the lens and determines depth of field. Low f-numbers (f/1.8) create shallow DOF with creamy bokeh. High f-numbers (f/11) keep the whole scene sharp.",
    "Shutter Speed & Motion": "Shutter speed controls exposure duration. Fast speeds (1/1000s) freeze motion. Slow speeds (1/30s) create motion blur for waterfalls or light trails. Use a tripod for anything below 1/60s.",
    "ISO & Noise": "ISO measures sensor sensitivity. Higher ISO brightens the image but introduces grain. Use the lowest native ISO possible; raise it only when aperture and shutter can't get enough light.",
    "Rule of Thirds": "Divide the frame into a 3x3 grid. Place subjects and horizons on the lines and intersections rather than dead-centre. This creates balanced, dynamic compositions that draw the viewer's eye naturally.",
    "Golden Hour": "The hour after sunrise and before sunset produces warm, directional, soft light. Shadows are long and colours are rich. Scout your location the day before so you're ready when the light is perfect.",
    "Studio Lighting Setup": "Three-point lighting (key, fill, back) gives full control. The key light is the main source; fill reduces shadows; back light separates the subject from the background. Use reflectors to redirect light cheaply.",
    "Natural Light Portraits": "Position your subject near a large window for soft, directional light. A white reflector on the shadow side fills in unflattering shadows. Overcast days are ideal — the clouds act as a giant softbox.",
    "Lightroom Workflow": "Import → cull → develop → export. In the Develop module, fix exposure first, then white balance, then colour grading. Use the Histogram to avoid clipping. Sync settings across a batch in one click.",
    "Color Grading": "Colour grading sets the mood. Use the HSL panel to shift individual hues, the Tone Curve for contrast, and the Colour Grading panel for shadows/midtones/highlights colour. Save presets for consistency.",
    "Skin Retouching": "Use the Spot Removal tool to remove blemishes. The Adjustment Brush lets you selectively brighten eyes, smooth skin with Clarity reduction, and sharpen details. Aim for natural, not over-processed.",
    "Exporting for Web & Print": "For web: export JPEG at 80% quality, sRGB colour space, 72 ppi, max 2000px on the long edge. For print: export TIFF at 300 ppi, Adobe RGB. Always keep the RAW master file.",
    "Pandas DataFrames": "A DataFrame is a 2D labelled data structure. Load CSVs with pd.read_csv(), inspect with .head(), .info(), and .describe(). Select columns with [] and rows with .loc[] (labels) or .iloc[] (positions).",
    "Data Cleaning Techniques": "Real data is messy. Handle missing values with .fillna() or .dropna(). Remove duplicates with .drop_duplicates(). Fix data types with .astype(). Detect outliers with IQR or z-score methods.",
    "Merging & Grouping": "Combine DataFrames with pd.merge() (like SQL JOIN) or pd.concat(). Use .groupby() with aggregation functions (.mean(), .sum(), .count()) to compute group-level statistics quickly.",
    "Time Series Analysis": "Parse dates with pd.to_datetime() and set as index. Resample with .resample('M').mean() for monthly aggregates. Use rolling windows for smoothed trends. Detect seasonality with seasonal decomposition.",
    "Matplotlib Basics": "Matplotlib is Python's foundational plotting library. plt.plot() for lines, plt.bar() for bars, plt.scatter() for scatter plots. Always label axes, add a title, and use plt.tight_layout() to prevent overlap.",
    "Seaborn Statistical Plots": "Seaborn builds on Matplotlib with high-level functions: sns.histplot(), sns.boxplot(), sns.heatmap(), sns.pairplot(). It integrates with DataFrames and applies attractive default styles automatically.",
    "Interactive Plotly Charts": "Plotly creates interactive charts renderable in browsers and Jupyter. Use px.line(), px.bar(), px.scatter() from Plotly Express. Add hover data, dropdowns, and sliders for exploratory dashboards.",
    "Dashboard with Streamlit": "Streamlit turns Python scripts into web apps in minutes. Use st.title(), st.dataframe(), st.plotly_chart(). Deploy to Streamlit Cloud for free. It re-runs the script top-to-bottom on every user interaction.",
    "Keyword Research": "Identify terms your audience searches for using Google Keyword Planner, Ahrefs, or SEMrush. Target long-tail keywords with lower competition. Map keywords to pages — one primary keyword per page.",
    "On-Page SEO": "Optimise title tags (under 60 chars), meta descriptions (under 160 chars), H1 headings, URL slugs, and image alt text. Place the primary keyword near the beginning of the title and in the first paragraph.",
    "Link Building": "Backlinks from authoritative sites boost your domain authority. Earn links through guest posting, digital PR, broken link building, and creating shareable assets (tools, infographics, original research).",
    "Technical SEO Audit": "Check crawlability with Google Search Console. Fix broken links (404s), improve page speed (Core Web Vitals), ensure mobile-friendliness, implement structured data (Schema.org), and add an XML sitemap.",
    "Google Ads Setup": "Create a campaign, choose a goal (sales, leads, traffic), set a daily budget, and write ads with strong headlines and CTAs. Use match types to control when ads show: exact, phrase, and broad match.",
    "Meta Ads Manager": "Build audiences using demographics, interests, behaviours, and Custom Audiences (email lists, website visitors). A/B test creative and copy. Monitor ROAS (Return on Ad Spend) and CPM to optimise spend.",
    "Retargeting Campaigns": "Retarget visitors who didn't convert using the Meta Pixel or Google Tag. Show personalised ads based on pages viewed or products seen. Retargeting audiences are warmer and convert at far higher rates.",
    "ROI & Attribution": "Attribution models assign credit to touchpoints. Last-click is simple but misleading. Data-driven attribution (available in GA4) uses ML to distribute credit. Track ROI = (Revenue - Cost) / Cost × 100.",
    "Content Calendar Strategy": "A content calendar aligns content to business goals and audience needs. Plan topics by keyword intent, map to buyer journey stages (awareness, consideration, decision), and publish consistently.",
    "Copywriting for Conversions": "Effective copy addresses the reader's pain, presents your solution as the cure, and removes friction. Use the AIDA framework (Attention, Interest, Desire, Action). Write benefits, not features.",
    "Email Sequences": "Welcome sequences nurture new subscribers over 5–7 emails. Provide value first; sell later. Segment by behaviour (opened, clicked, purchased). Use A/B testing on subject lines to optimise open rates.",
    "Analytics with GA4": "GA4 uses an event-based model. Set up conversion events, explore user journeys in the Funnel Exploration report, and use the Looker Studio connector for shareable dashboards with custom KPIs.",
    "Compound Components": "Compound components share implicit state through React Context. The parent manages state; children access it without explicit prop passing. Used by libraries like Radix UI and Headless UI for flexible APIs.",
    "Render Props": "Render props pass a function as a prop that returns JSX, giving the parent control over what the child renders. Enables powerful code reuse. Largely superseded by hooks, but still useful in some patterns.",
    "Custom Hooks": "Extract stateful logic into custom hooks (useLocalStorage, useFetch, useDebounce) to share behaviour across components without changing the component tree. Hooks must start with 'use' by convention.",
    "Higher-Order Components": "An HOC wraps a component and returns an enhanced version — adding props, data, or behaviour. Common for cross-cutting concerns like auth guards and analytics tracking. Prefer hooks in modern code.",
    "React.memo & useMemo": "React.memo prevents re-renders when props haven't changed. useMemo caches expensive computed values. useCallback caches function references. Profile first — premature optimisation adds complexity for little gain.",
    "Code Splitting": "Code splitting with React.lazy() and Suspense loads bundles on demand, reducing initial JS payload. Use route-level splitting as a baseline. Webpack and Vite both support dynamic import() automatically.",
    "Virtualization": "Virtualisation renders only visible rows in long lists. Use react-window or react-virtual. Essential for tables with 1000+ rows where rendering all DOM nodes causes severe performance degradation.",
    "Bundle Analysis": "Use webpack-bundle-analyzer or Vite's rollup-plugin-visualizer to see what's bloating your bundle. Common culprits: moment.js (replace with date-fns), lodash (use tree-shaking), large image imports.",
    "Context at Scale": "Context re-renders all consumers when the value changes. Split contexts by update frequency (ThemeContext, AuthContext, DataContext). Use useMemo to stabilise the value object and avoid unnecessary renders.",
    "Zustand": "Zustand is a minimal state manager using a hook-based API. Create a store with create(), select slices with the selector pattern, and use immer middleware for immutable updates. No providers needed.",
    "React Query": "React Query handles server state: fetching, caching, background updates, and stale-while-revalidate. useQuery fetches data; useMutation manages writes. Eliminates most manual useEffect data-fetching code.",
    "Optimistic Updates": "Optimistic updates apply changes to the UI immediately and roll back on error, making apps feel instant. React Query's onMutate callback lets you update the cache before the server responds.",
    "Brand Discovery Workshop": "Start every brand project with discovery: interview stakeholders, audit competitors, and survey customers. Uncover the brand's core purpose, values, and personality before touching any design tools.",
    "Competitive Analysis": "Map competitors on axes of positioning (premium vs accessible, playful vs serious). Identify white space — areas underserved by competitors where your brand can stand out authentically.",
    "Positioning & Differentiation": "Positioning is the unique space your brand occupies in customers' minds. Define your target audience, category, key benefit, and reason to believe. Differentiation is why customers choose you over others.",
    "Moodboarding": "A moodboard collects visual references (photography, typography, colour, texture) that capture the desired brand feeling. It aligns stakeholders on direction before committing to design execution.",
    "Logo Design Process": "Start with sketches, explore 20+ concepts, refine three directions digitally. A great logo works in black and white, at 16px and billboard scale. Test it on real backgrounds and products before finalising.",
    "Typography System": "A type system pairs a display font (for headlines) with a body font (for text). Define a modular scale (e.g. 12/14/16/20/24/32/48px), line heights, and weights. Limit to 2–3 typefaces maximum.",
    "Color Palette": "Build a palette with one primary, one secondary, and 2–3 neutral shades. Define semantic colours: success (green), warning (amber), error (red). Ensure WCAG AA contrast ratios for accessibility.",
    "Photography Style": "Art-directed photography reinforces brand personality. Define composition style, subject matter, colour temperature, and editing treatment. Create a do/don't reference sheet for photographers and agencies.",
    "Brand Guidelines Structure": "Guidelines include: logo usage rules, clear space, minimum sizes, colour palette with HEX/RGB/CMYK/Pantone values, typography specimens, photography style, and tone-of-voice principles.",
    "Component Library": "A component library codifies the design system in Figma with shared styles and auto-layout components. Mirror it in code (Storybook). Keep design and code in sync with a shared token system.",
    "Client Presentation": "Present three distinct concepts, not one polished answer. Walk clients through your rationale before showing the design. Ask for reactions, not approval. Document feedback and decision owners.",
    "Brand Rollout": "Rollout order: brand guidelines → digital (website, social templates) → print (business cards, letterhead) → signage. Run a brand audit after 90 days to ensure consistent application across all touchpoints.",
    "How VC Funds Work": "VC funds raise capital from LPs (pension funds, endowments, family offices), deploy it into startups over 3–5 years, and return capital via exits (IPO, M&A) over a 10-year fund life. GPs earn 2% management fee and 20% carried interest.",
    "Deal Sourcing": "Top VCs source deals via founder networks, accelerators (YC, Techstars), scout programmes, and conference circuits. The best deals are often referrals from portfolio founders. Build relationships before you need them.",
    "Due Diligence": "DD covers: team (background checks, references), market size (TAM/SAM/SOM), product (technical review, IP), traction (MoM growth, retention, NPS), financials, and legal (cap table, contracts).",
    "Cap Table Basics": "The cap table tracks equity ownership. Founders start with 100%; each funding round dilutes everyone. Options pool (10–20%) incentivises employees. Use SAFE notes to defer valuation conversations at seed stage.",
    "Pre-money vs Post-money": "Pre-money valuation is the company's value before investment. Post-money = pre-money + investment. A $10M pre-money raise of $2M results in a $12M post-money valuation and ~16.7% investor ownership.",
    "Term Sheet Negotiation": "Key terms: valuation, pro-rata rights, board seats, information rights, liquidation preference (1x non-participating is founder-friendly), anti-dilution (broad-based weighted average is standard).",
    "Dilution & Options": "Every new round dilutes existing shareholders. Model dilution in a spreadsheet before signing. Options vest over 4 years with a 1-year cliff. Strike price should equal FMV at grant date to avoid tax issues.",
    "SAFE vs Priced Rounds": "SAFEs (Simple Agreement for Future Equity) delay valuation to the next priced round, converting at a discount or with a valuation cap. They're faster and cheaper than priced rounds but defer tough conversations.",
    "Location Scouting": "Research locations using Google Maps satellite view, the Photographer's Ephemeris app for sun angles, and 500px or Instagram for visual inspiration. Visit at different times of day to assess light quality.",
    "Golden Hour & Blue Hour": "Golden hour lasts roughly 30 minutes after sunrise and before sunset — warm, low, directional light. Blue hour follows sunset: the sky turns deep blue with balanced ambient and artificial light. Set alarms; it's brief.",
    "Weather & Light Planning": "Dramatic clouds, mist, and storms create compelling landscapes. Apps like Windy, Clear Outside, and Meteoblue forecast cloud cover, fog, and precipitation. Overcast light is soft and even — embrace it.",
    "Gear for Landscapes": "Essentials: a sturdy tripod, remote shutter release, circular polariser (cuts glare, boosts saturation), ND filters (6-stop, 10-stop for long exposures), and wide-angle lens (14–24mm on full frame).",
    "Long Exposure Basics": "Use a tripod, remote release, and mirror lockup (DSLRs) to eliminate vibration. Set ISO 100, f/8–f/11, and choose a shutter speed that smooths water or clouds. Expose to the right to minimise noise.",
    "ND Filters": "Neutral density filters reduce light without affecting colour, enabling slow shutter speeds in bright conditions. A 10-stop ND turns a 1/100s exposure into a 10-second blur. Stack filters with care to avoid colour cast.",
    "Focus Stacking": "For macro and landscape, focus stacking blends multiple exposures focused at different depths to achieve infinite sharpness front-to-back. Shoot in aperture priority, step focus manually, merge in Photoshop or Helicon Focus.",
    "Panoramic Stitching": "Shoot in portrait orientation, overlap frames by 30–40%, use a nodal point head to avoid parallax errors, and shoot in manual mode for consistent exposure. Stitch in Lightroom or PTGui for high-resolution results.",
    "RAW Processing Workflow": "Always shoot RAW for maximum flexibility. Correct lens distortion and chromatic aberration first. Adjust exposure, white balance, and tone, then apply noise reduction and sharpening last to avoid compounding artefacts.",
    "Sky Replacement": "Photoshop's Sky Replacement (Edit > Sky Replacement) uses AI to mask and blend a new sky seamlessly. Match the colour temperature of the ground to the new sky using a gradient map or colour grading layer.",
    "Dodging & Burning": "Dodging lightens areas; burning darkens them. Create a 50% grey layer set to Overlay blend mode and paint with white (dodge) or black (burn) to add volume, guide the eye, and enhance three-dimensionality.",
    "Signature Style Development": "Your style emerges from consistent creative choices: subject matter, colour palette, contrast level, mood, and time of day. Shoot 10,000 images before worrying about style — it develops naturally through repetition.",
}

class Command(BaseCommand):
    help = "Add textual content to all seeded lessons based on their title."

    def handle(self, *args, **options):
        updated = 0
        skipped = 0
        for lesson in Lesson.objects.all():
            content = CONTENT.get(lesson.title)
            if content:
                lesson.content = content
                lesson.save(update_fields=["content"])
                updated += 1
            else:
                skipped += 1
        self.stdout.write(self.style.SUCCESS(f"✓ Updated {updated} lessons, skipped {skipped} (no match)."))
